# Generated by Django 3.0.6 on 2020-06-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_detail_in_products_list_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_products',
            name='obj_details',
        ),
        migrations.DeleteModel(
            name='Detail_in_products',
        ),
        migrations.DeleteModel(
            name='List_products',
        ),
    ]
