# Generated by Django 3.0.6 on 2020-07-08 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0010_auto_20200622_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_in_products',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='sklad.List_details', verbose_name='детали'),
        ),
        migrations.AlterField(
            model_name='list_products',
            name='obj_details',
            field=models.ManyToManyField(blank=True, default='default_obj_details', null=True, to='sklad.Detail_in_products', verbose_name='детали'),
        ),
    ]
